config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :items

  root 'homes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  respond_to :json
end

app/controllers/categories_controller.rb
# encoding: utf-8

class CategoriesController < ApplicationController
  layout 'others'
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/homes_controller.rb
# encoding: utf-8

class HomesController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/items_controller.rb
# encoding: utf-8

class ItemsController < ApplicationController
  layout 'others'
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html


  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    respond_with(@items) do |format|
      format.json { render :json => @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sss_categories_helper.rb
module SssCategoriesHelper
end

app/helpers/ssses_helper.rb
module SssesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><center>Listing Categories</center></h1>
<div class="col-md-8 col-md-offset-2" style="margin-bottom:50px">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <center><%= link_to 'New Category', new_category_path, class:"btn btn-default" %></center>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/homes/index.html.erb
<div ng-controller="ListController">
  <div class="categories" ng-controller="CategoryController">
    <div class="col-md-4">
      <center><h3>Kategoriler</h3></center>
      <span ng-repeat="category in categories">
        <div class="col-lg-12">
          <div class="btn-group btn-group-justified">
            <div ng-click="sendCategory(category)" class="btn btn-primary" style="padding:10px">{{category.name}}</div>
          </div>
        </div>
      </span>
      <div class="col-lg-12">
        <div class="btn-group btn-group-justified">
          <div ng-click="resetSearch()" class="btn btn-primary" style="padding:10px">Select All</div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <center><h3>Kategoriler (Checkbox)</h3></center>
      <label ng-repeat="category in categories">
        <input
          type="checkbox"
          name="selectedFruits[]"
          value="{{category}}"
          ng-checked="selection.indexOf(category.id) > -1"
          ng-click="toggleSelection(category.id)"> {{category.name}}
      </label>
      <pre>{{selection|json}}</pre>
    </div>
  </div>

  <div class="col-md-8 col-md-offset-2">
    <br>
    <input ng-model="yaz" placeholder="Search..." class="form-control"/>
    <br>
    <div class="left" ng-controller="ItemController">
      <div class="itemList">
        <div class="panel panel-default" ng-repeat="item in items | filter:{category_id:search } | filter:yaz | filterWithOr:{category_id: selection}">
          <div class="panel-heading">
            <h4>{{item.title}}</h4>
          </div>
          <div class="panel-body">
            <p>{{item.description}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
  <%= f.association :category, label: "Kategoriler" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1><center>Listing Items</center></h1>
<div class="col-md-12" style="margin-bottom:50px">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.title %></td>
          <td><%= item.description %></td>
          <td><%= item.price %></td>
          <td><%= item.category_id %></td>
          <td><%= link_to 'Show', item %></td>
          <td><%= link_to 'Edit', edit_item_path(item) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <center><%= link_to 'New Item', new_item_path, class:"btn btn-default" %></center>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category.name%>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>Filter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.5/angular-route.min.js"%>

  <%= csrf_meta_tags %>
</head>
<body style="background-color:#585858">
  <div class="container" style="background-color:#D8D8D8">
    <%= render "shared/header" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/filter.html.erb
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>Filter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.5/angular-route.min.js"%>
  
  <%= csrf_meta_tags %>
</head>
<body>

 <ng-view></ng-view>
</body>
</html>

app/views/layouts/others.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.5/angular-route.min.js"%>

  <%= csrf_meta_tags %>
</head>
<body style="background-color:#585858">
  <div class="container" style="background-color:#D8D8D8">
    <%= render "shared/header" %>
    <div class="col-md-8 col-md-offset-2" style="margin-bottom:50px">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Rails Filter With AngularJS', '/#/home', class:"navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'New Item', new_item_path %></li>
      <li><%= link_to 'New Category', new_category_path %></li>
    </ul>
  </div><!--/.container-fluid -->
</nav>